spring:
  application:
    name: ticketing-platform
  datasource:
    # URL подключения к базе данных
    # Для Docker: jdbc:postgresql://postgres:5432/tickets (postgres - имя сервиса в docker-compose)
    # Для локального запуска: jdbc:postgresql://localhost:15432/tickets (15432 - внешний порт)
    url: ${DB_URL:jdbc:postgresql://localhost:15432/tickets}
    username: ${DB_USERNAME:ticket}
    password: ${DB_PASSWORD:ticket}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  mail:
    host: smtp.timeweb.ru
    port: 465
    username: info@surnekevents.ru
    password: zy287rt3f7
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.timeweb.ru
  jackson:
    default-property-inclusion: non_null
  web:
    resources:
      add-mappings: false
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: INFO
    com.surnekev.ticketing: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

security:
  jwt:
    issuer: ticketing-platform
    access-token-ttl-seconds: ${JWT_TTL_SECONDS:1800}
    secret: ${JWT_SECRET:DeaukxWN9xJ5qe5AtwBOBDXgdJ13qEBPgf408F6EFjrXs2H/Bc9LkeAKCA+SjFBL}

admin:
  default-password: ${ADMIN_DEFAULT_PASSWORD:12345}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:7805509546:AAEYNWvv9Bt90qyTM51ZTg0I6X0tIw0wP1o}
  manager-chat-id: ${TELEGRAM_CHAT_ID:8530131432}

seatmap:
  hold-ttl-seconds: 1800

mail:
  from: ${MAIL_FROM:info@surnekevents.ru}
